Repository longturn/freeciv21, pull requests merged in 2022-08, with the labels that each got.

#1171 Introduce a map renderer class
  client/CMakeLists.txt
  client/mapview.cpp
  client/mapview.h
  client/page_game.cpp
  client/renderer.cpp
  client/renderer.h
Labels: refactoring, client

#1168 Remove static calls to units_reports
  client/dialogs.cpp
  client/include/repodlgs_g.h
  client/menu.cpp
  client/page_game.cpp
  client/page_game.h
  client/top_bar.cpp
  client/unitreport.cpp
  client/unitreport.h
Labels: refactoring, client

#1165 Get rid of fileinfo and fileinfo_list
  client/page_load.cpp
  client/page_scenario.cpp
  server/stdinhand.cpp
  utility/shared.cpp
  utility/shared.h
Labels: refactoring

#1188 Use std::vector for the list of focused units
  client/citydlg.cpp
  client/client_main.cpp
  client/climisc.cpp
  client/climisc.h
  client/control.cpp
  client/control.h
  client/dialogs.cpp
  client/dialogs.h
  client/goto.cpp
  client/goto.h
  client/gotodlg.cpp
  client/hudwidget.cpp
  client/include/dialogs_g.h
  client/include/mapview_g.h
  client/mapctrl_common.cpp
  client/mapview.cpp
  client/menu.cpp
  client/packhand.cpp
  client/text.cpp
  client/text.h
  client/tilespec.cpp
  common/unitlist.cpp
  common/unitlist.h
Labels: refactoring

#1183 Use compile_commands.json with clang-tidy
  .github/workflows/clang-tidy.yaml
Labels: bug, tools

#1172 Resize the canvas a bit less often in map_canvas_resized
  client/mapview_common.cpp
Labels: refactoring, client

#1298 Update database script to load external lua modules
  lua/database.lua
Labels: bug, server
