Repository longturn/freeciv21, pull requests merged in 2024-09, with the labels that each got.

#2379 Release Action Updates
  .github/workflows/release.yaml
Labels: back-port

#2387 fix wrong unit being linked to stack kill message
  server/unittools.cpp
Labels: bug, server

#2393 Fix drawing AllSeparate roads in hex mode
  client/tileset/layer_roads.cpp
Labels: bug, gui
